Billing/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('billing/', views.customer_list, name='customer_list'),
    path('<int:customer_id>/edit/', views.edit_customer, name='edit-customer.html'),
    path('billing/add_customer/', views.add_new_customer, name='add_new_customer'),
    path('billing/get-gst-report/', views.get_gst_report, name='get-gst-report'),
    path('billing/get-sales-report/', views.get_sales_report, name='get_sales_report'),
    path('billing/get-gst-report/export_csv/', views.export_report_to_csv, name='export_report_to_csv'),
    path('billing/add_customer/<int:customer_id>/extended/', views.customer_extended_form, name='customer_extended_form'),

    path('billing/<int:customer_id>/orders/', views.order_list, name='order_list'),
    path('ledger_view/<int:customer_id>/', views.ledger_view, name='ledger_view'),
    path('generate_ledger/<int:customer_id>/<str:start_date>/<str:end_date>/', views.generate_ledger, name='generate_ledger'),
    path('billing/<int:customer_id>/orders/<int:order_id>/delete/', views.order_delete, name='order_delete'),
    path('billing/<int:customer_id>/orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('billing/<int:customer_id>/orders/<int:order_id>/register_sales_return/', views.register_sales_return, name='register_sales_return'),
    path('billing/<int:customer_id>/orders/<int:order_id>/sales_return/<int:sales_return_id>/', views.returned_items,
         name='returned_items'),
    path('billing/<int:customer_id>/order/<int:order_id>/cash/', views.order_paid_cash, name='order_paid_cash'),
    path('billing/<int:customer_id>/order/<int:order_id>/upi/', views.order_paid_upi, name='order_paid_upi'),
    path('billing/<int:customer_id>/order/<int:order_id>/net-banking/', views.order_paid_net, name='order_paid_net'),
    path('billing/<int:customer_id>/order/<int:order_id>/cheque/', views.order_paid_cheque, name='order_paid_cheque'),
    path('billing/<int:customer_id>/orders/<int:order_id>/<int:order_item_id>/edit/', views.order_item_edit, name='order_item_edit'),
    path('billing/<int:customer_id>/orders/<int:order_id>/<int:order_item_id>/delete/', views.order_item_delete, name='order_item_delete'),
    path('billing/<int:order_id>/invoice/', views.generate_invoice),
    path('invoice/<int:order_id>/', views.invoice),
]

Formee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Users.views import index_request

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_request),
    path('', include('Stock.urls')),
    path('', include('Users.urls')),
    path('', include('Billing.urls')),
    path('', include('Accounting.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Stock/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view),
    path('stock/', views.stock_view),
    path('stock/add_product/', views.add_product_view),
    path('stock/product/<str:code>/', views.edit_product_view),
    path('stock/stock_report/', views.stock_report),
    path('stock/generate_quantity_summary_csv/', views.generate_quantity_summary_csv, name='generate_quantity_summary_csv'),
]

Billing/models.py
from Stock.models import Product
from django.db import models
from django.db.models import Sum


SALE_CHOICE = (
    ('super market', 'Distributor'),
    ('franchise', 'Franchise'),
    ('normal', 'Normal Customer'),
    ('exhibition', 'Exhibition'),
)


class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    district = models.CharField(max_length=100, default='')
    state = models.CharField(max_length=20, default='Maharashtra')
    email = models.EmailField()
    gstin = models.CharField(max_length=100)
    fssai = models.CharField(max_length=100)
    phone = models.PositiveBigIntegerField()
    birth_date = models.CharField(max_length=10, default="")
    order_type = models.CharField(max_length=30, choices=SALE_CHOICE, default='normal')
    franchise_id = models.CharField(default="", max_length=5)

    def __str__(self):
        return self.name

    @property
    def no_of_order(self):
        return self.order_set.count()


class Order(models.Model):
    created_at = models.DateTimeField(auto_now_add=False, editable=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='OrderItem')
    order_total = models.FloatField(default=0)
    payment_status = models.CharField(max_length=30, default='Pending')
    payment_type = models.CharField(max_length=20, default='')
    discount = models.PositiveIntegerField(default=0, null=True, blank=True)
    delivery = models.FloatField(default=0, null=True, blank=True)
    invoice_number = models.PositiveIntegerField(default=0, blank=True, null=True)
    payment_terms = models.CharField(max_length=100, default='', blank=True, null=True)
    ref_number = models.CharField(default='', max_length=24, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.order_total = max(0, self.order_total)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.customer} - {self.id}"

    def cgst(self):
        return self.order_total * 6 / 100

    def sgst(self):
        return self.order_total * 6 / 100

    def igst(self):
        if self.customer.state != 'Maharashtra':
            return self.order_total * 12 / 100
        else:
            return 0

    def total_gst(self):
        if self.customer.state != 'Maharashtra':
            return self.igst()
        else:
            return self.sgst() + self.cgst()

    def order_total_with_gst(self):
        return round(self.order_total + self.total_gst(), 0)

    def normal_order_total(self):
        total = self.order_total
        rounded_total = total.__round__(0)
        return rounded_total

    def order_total_with_delivery(self):
        total = round(self.order_total + self.delivery, 0)
        return total

    def order_total_with_gst_and_delivery(self):
        return round(self.order_total_with_gst() + self.delivery, 0)

    def real_order_total(self):
        real = round((self.order_total * 100) / (100 - self.discount), 0)
        return real

    def discount_amount(self):
        return self.real_order_total() - self.order_total

    def get_total_amount_based_on_type(self):
        if self.customer.order_type == 'normal':
            return self.order_total
        else:
            return self.order_total_with_gst()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField(default=0)
    batchno = models.CharField(max_length=20, default='')

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

    def item_total(self):
        return self.price * self.quantity


class SalesReturn(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    sales_return_total = models.FloatField(default=0.0)

    def update_sales_return_total(self):
        total_return = self.returnitem_set.aggregate(total=Sum('return_total'))['total']
        self.sales_return_total = round(total_return, 2)
        self.save()

    def __str__(self):
        return f"Return for Order {self.order.id} by {self.customer.name}"


class ReturnItem(models.Model):
    sales_return = models.ForeignKey(SalesReturn, on_delete=models.CASCADE)
    product = models.ForeignKey(OrderItem, on_delete=models.CASCADE, default=None)
    quantity = models.PositiveIntegerField(default=1)
    return_total = models.FloatField(default=0)
    payment_status = models.CharField(max_length=30, default='')
    payment_type = models.CharField(max_length=20, default='')
    price = models.FloatField(default=0)

    def __str__(self):
        return f"ReturnItem of {self.sales_return.id} - {self.id}"

Billing/forms.py
from django import forms
from .models import *
from Stock.models import Product

SALE_CHOICE = (
    ('normal', 'Normal Customer'),
    ('super market', 'Distributor'),
    ('franchise', 'Franchise'),
    ('exhibition', 'Exhibition'),
)


class CustomerForm(forms.ModelForm):
    name = forms.CharField()
    phone = forms.IntegerField(required=False)
    birth_date = forms.CharField(required=False)
    no_of_order = forms.IntegerField(required=False)
    order_type = forms.ChoiceField(choices=SALE_CHOICE, required=False)

    class Meta:
        model = Customer
        fields = ['name', 'phone', 'birth_date', 'no_of_order', 'order_type']


class CustomerProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea)
    district = forms.CharField(required=False)
    state = forms.CharField(required=False)
    email = forms.CharField(required=False)
    gstin = forms.CharField(required=False)
    fssai = forms.CharField(required=False)
    franchise_id = forms.CharField(required=False)

    class Meta:
        model = Customer
        fields = ['address', 'district', 'state', 'email', 'gstin', 'fssai', 'franchise_id']


class OrderForm(forms.ModelForm):
    created_at = forms.DateField(label='Created at', widget=forms.DateInput(attrs={'type': 'date'}),
                                 input_formats=['%Y-%m-%d'])
    payment_status = forms.CharField(required=False)
    invoice_number = forms.IntegerField(required=False)
    ref_number = forms.CharField(required=False)

    class Meta:
        model = Order
        fields = ('created_at', 'payment_status', 'invoice_number', 'ref_number')

    def clean_created_at(self):
        created_at = self.cleaned_data['created_at']
        return created_at


class DeliveryForm(forms.ModelForm):
    delivery = forms.FloatField(required=False)
    discount = forms.IntegerField(required=False)
    payment_terms = forms.CharField(required=False)

    class Meta:
        model = Order
        fields = ['delivery', 'discount', 'payment_terms']

    def __init__(self, *args, **kwargs):
        order = kwargs.pop('order', None)
        super().__init__(*args, **kwargs)
        if order:
            self.fields['payment_terms'].widget.attrs.update({'placeholder': order.payment_terms})


class OrderItemForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all().order_by('code'), label='Product', to_field_name='id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].label_from_instance = lambda obj: f"{obj.barcode} - {obj.size} - {obj.name}"

    class Meta:
        model = OrderItem
        fields = ('product', 'quantity', 'price', 'batchno',)


class ReturnedItemForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=None)
    quantity = forms.IntegerField(initial=1)

    class Meta:
        model = ReturnItem
        fields = ['product', 'quantity']

    def __init__(self, order_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        order_items = OrderItem.objects.filter(order_id=order_id)
        self.fields['product'].queryset = order_items
        self.fields['product'].label_from_instance = lambda obj: f"{obj.product.barcode} - {obj.product.size} - {obj.product.name}"
        def clean(self):
            cleaned_data = super().clean()
            product = cleaned_data.get('product')
            quantity = cleaned_data.get('quantity')
            return cleaned_data


class SalesReturnForm(forms.ModelForm):
    class Meta:
        model = SalesReturn
        fields = '__all__'

    def __init__(self, order_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        order_items = OrderItem.objects.filter(order_id=order_id)
        self.fields['returned_items'].queryset = order_items

Billing/templates/add_new_customer.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-4/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Add New Customer</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="flex gap-16 my-6">
            <div class="w-1/2">
                <p class="text-xl my-2">Customer Type</p>
                {% render_field form.order_type class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Nashik" %}
            </div>
            <div class="w-1/2">
                <p class="text-xl my-2">Customer Name</p>
                {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Eg: Formee Foods" %}
            </div>
        </div>

        <div class="flex my-6 gap-16">
            <div class="w-1/2">
                <p class="text-xl my-2">Phone</p>
                {% render_field form.phone class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="9840239390" %}
            </div>
            <div class="w-1/2">
                <p class="text-xl my-2">Date of Birth</p>
                {% render_field form.birth_date class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="13/11" %}
            </div>
        </div>

        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Add
            Customer
        </button>
    </form>
</div>

{% endblock %}

Billing/templates/billing.html
{% extends 'base.html' %}

{% block body %}


<div class="m-auto w-11/12 mt-4 p-2 border rounded flex flex-row justify-between items-center shadow-md">
    <div>
        <a href="add_customer/">
            <button type="button" class="mr-1 m-2 px-4 py-2 bg-green-400 rounded">Add New Customer</button>
        </a>
    </div>
    <div>
        <a href="get-gst-report/">
            <button type="button" class="ml-1 m-2 px-4 py-2 bg-green-400 rounded">Get GST Report</button>
        </a>
    </div><div>
        <a href="get-sales-report/">
            <button type="button" class="ml-1 m-2 px-4 py-2 bg-green-400 rounded">Get Sales Report</button>
        </a>
    </div>
    <div class="grow ml-6">
        <form action="">
            <input type="text" class="w-[100%] h-10 border indent-4 rounded" name="customer_search"
                   placeholder="Search Customer">
    </div>
    <div>
        <button type="submit" class="m-2 px-4 py-2 bg-green-400 rounded">Search</button>
        </form>
    </div>

</div>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg w-11/12 m-auto mt-4">
    <table class="w-full text-sm text-left border">
        <thead class="text-xs uppercase">
        <tr>
            <th scope="col" class="px-6 py-3">
                Id
            </th>
            <th scope="col" class="px-6 py-3">
                Customer name
            </th>
            <th scope="col" class="px-6 py-3">
                Type
            </th>
            <th scope="col" class="px-6 py-3">
                District
            </th>
            <th scope="col" class="px-6 py-3">
                Phone
            </th>
            <th scope="col" class="px-6 py-3">
                No. of Orders
            </th>
            <th scope="col" class="px-6 py-3">
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
        <tr class="bg-white border-b">
            <td class="px-6 py-4">
                {{ customer.id }}
            </td>
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                {{ customer.name }}
            </th>
            <td class="px-6 py-4">
                {{ customer.order_type|title }}
                {% if customer.franchise_id and customer.franchise_id != '0' %}
                <span class="text-xs">({{ customer.franchise_id }})</span>
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {{ customer.district }}
            </td>
            <td class="px-6 py-4">
                {{ customer.phone }}
            </td>
            <td class="px-6 py-4">
                {{ customer.no_of_order }}
            </td>
            <td class="px-6 py-4">
                <a href="{{ customer.id }}/orders/" class="font-medium text-blue-600 hover:underline">View</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div class="w-11/12 m-auto my-10">
    <p class="mx-2">Page: {{ customers.number }} of {{ customers.paginator.num_pages}}</p>
    <br>
    {% if customers.has_previous %}
    <a href="?page={{ customers.previous_page_number }}">Previous</a>
    {% endif %}
    {% for pages in customers.paginator %}
    <a href="?page={{ forloop.counter }}">
        <button class="w-[35px] h-10 rounded mx-2 bg-green-400">{{ forloop.counter }}</button>
    </a>
    {% endfor %}
    {% if customers.has_next %}
    <a href="?page={{ customers.next_page_number }}">Next</a>
    {% endif %}

    <br><br>

</div>


{% endblock %}

Billing/templates/get-gst-report.html
{% extends 'base.html' %}
{% include math %}

{% block body %}
<style>
.sticky-header {
  position: sticky;
  top: 0;
  z-index: 50;
}
</style>

<div class="m-auto w-11/12 mt-4 px-2 border rounded flex flex-row justify-between items-center shadow-md">
    <div class="text-xl font-bold">
        <a href="/billing/" class="text-blue-600 hover:underline">Billing</a> >
        <a href="/billing/get-gst-report/" class="text-purple-600 hover:underline">Get GST Report</a>
    </div>
    <form method="GET" action="{% url 'export_report_to_csv' %}">
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" name="start_date" class="h-10 border indent-1 rounded">

        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" class="h-10 border indent-1 rounded">

        <button type="submit" class="px-4 py-2 bg-green-400 rounded m-2">Export to CSV</button>
    </form>

</div>

<div class="overflow-x-auto shadow-md sm:rounded-lg w-11/12 m-auto mt-4 flex flex-col h-screen">
    <table class="relative w-full text-sm text-left border flex-grow overflow-auto">
        <thead class="text-xs uppercase">
        <tr>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                SR. No.
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Invoice Number
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Invoice Date
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Customer
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Customer GSTIN
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Order Total<br>
                <span class="text-blue-600">{{ total_real_order_total|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                CGST<br>
                <span class="text-blue-600">{{ total_cgst|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                SGST<br>
                <span class="text-blue-600">{{ total_sgst|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                IGST<br>
                <span class="text-blue-600">{{ total_igst|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Total GST<br>
                <span class="text-blue-600">{{ total_total_gst|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Total Amount<br>
                <span class="text-blue-600">{{ total_order_total_with_gst|floatformat:2 }}</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Payment Status<br>
            </th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr class="bg-white border-b">
            <td class="px-6 py-4">
                {{ forloop.counter }}
            </td>
            <td class="px-6 py-4">
                2024-25/{{ order.invoice_number }}
            </td>
            <th scope="row" class="px-6 py-4 font-medium text-gray-900">
                {{ order.created_at|date:"F d, Y" }}
            </th>
            <td class="px-6 py-4">
                {{ order.customer.name }}<span class="text-xs">({{ order.customer.get_order_type_display }})</span>
            </td>

            <td class="px-6 py-4">
                {% if order.customer.gstin %}
                {{ order.customer.gstin }}
                {% else %}
                -
                {% endif %}
            </td>

            <td class="px-6 py-4">
                {{ order.order_total|floatformat:2 }}
            </td>
            <td class="px-6 py-4">
                {% if order.customer.order_type != 'normal' %}
                {{ order.cgst|floatformat:2 }}
                {% else %}
                -
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {% if order.customer.order_type != 'normal' %}
                {{ order.sgst|floatformat:2 }}
                {% else %}
                -
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {% if order.customer.state != 'Maharashtra' %}
                {{ order.igst|floatformat:2 }}
                {% else %}
                -
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {% if order.customer.order_type != 'normal' %}
                {{ order.total_gst|floatformat:2 }}
                {% else %}
                -
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {% if order.customer.order_type != 'normal' %}
                {{ order.order_total_with_gst|floatformat:2 }}
                {% else %}
                {{ order.normal_order_total|floatformat:2 }}
                {% endif %}

                {% if order.discount %}
                (<span class="text-xs">{{ order.discount }}% disc.)</span>
                {% endif %}
            </td>
            <td class="px-6 py-4">
                {{ order.payment_status }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

Billing/templates/get_sales_report.html
{% extends 'base.html' %}
{% include math %}
{% load ledger_filters %}
{% block body %}

<div class="text-xl font-bold w-11/12 m-auto mt-6">
    <a href="/billing/" class="text-blue-600 hover:underline">Billing</a> >
    <a href="/billing/get-sales-report/" class="text-purple-600 hover:underline">Get Sales Report</a>
</div>

<div class="m-auto w-11/12 mt-4 px-2 border rounded shadow-md">
    <form method="GET" action="{% url 'get_sales_report' %}" class="flex flex-row justify-between items-center">

        <div>
            <input type="date" id="start_date" name="start_date" value="{{ request.GET.start_date }}" class="h-10 border indent-1 rounded">

            <input type="date" id="end_date" name="end_date" value="{{ request.GET.end_date }}" class="h-10 border indent-1 rounded">
        </div>

        <div>
            <label for="order_type"></label>
            <input type="checkbox" id="normal" name="order_type[]" value="normal" {% if 'normal' in request.GET.order_type %}checked{% endif %}>
            <label for="normal">Normal</label>
            <input type="checkbox" id="super_market" name="order_type[]" value="super market" {% if 'super market' in request.GET.order_type %}checked{% endif %}>
            <label for="super_market">Super Market</label>
            <input type="checkbox" id="franchise" name="order_type[]" value="franchise" {% if 'franchise' in request.GET.order_type %}checked{% endif %}>
            <label for="franchise">Franchise</label>
        </div>

        <div>
            <label for="payment_status"></label>
            <input type="checkbox" id="pending" name="payment_status[]" value="Pending" {% if 'Pending' in request.GET.payment_status %}checked{% endif %}>
            <label for="pending">Pending</label>
            <input type="checkbox" id="paid" name="payment_status[]" value="Paid" {% if 'Paid' in request.GET.payment_status %}checked{% endif %}>
            <label for="paid">Paid</label>
        </div>

        <div>
            <label for="payment_type">Payment Type:</label>
            <select name="payment_type" id="payment_type">
                <option value="">All</option>
                    {% for type in payment_types %}
                    <option value="{{ type }}" {% if request.GET.payment_type == type %}selected{% endif %}>{{ type }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" name="apply_filters" class="px-4 py-2 bg-green-400 rounded m-2">Apply Filters</button>
        <button type="submit" name="export_csv" class="px-4 py-2 bg-green-400 rounded m-2">Export to CSV</button>
    </form>


</div>

<div class="overflow-x-auto shadow-md sm:rounded-lg w-11/12 m-auto mt-4 flex flex-col h-screen">
    <table class="relative w-full text-sm text-left border flex-grow overflow-auto">
        <thead class="text-xs uppercase">
        <tr>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                SR. No.
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Invoice Number
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Invoice Date
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Customer
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Order Total(exl. gst)<br>
                <span class="text-blue-600">({{ total_sales|floatformat:2 }})</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Order Total(incl. gst)<br>
                <span class="text-blue-600">({{ total_sales_with_gst|floatformat:2 }})</span>
            </th>
            <th scope="col" class="sticky top-0 px-6 py-3 bg-gray-100">
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr class="bg-white border-b">
            <td class="px-6 py-4">
                {{ forloop.counter }}
            </td>
            <td class="px-6 py-4">
                2024-25/{{ order.invoice_number }}
            </td>
            <th scope="row" class="px-6 py-4 font-medium text-gray-900">
                {{ order.created_at|date:"d F, Y" }}
            </th>
            <td class="px-6 py-4 font-bold">
                {{ order.customer.name }}<span class="text-xs">({{ order.customer.get_order_type_display }})</span>
            </td>

            <td class="px-6 py-4">
                {{ order.order_total }}
            </td>

            <td class="px-6 py-4">
                {% if order.customer.order_type != 'normal' %}
                {{ order.order_total_with_gst|floatformat:2 }}
                {% elif order.customer.order_type == 'normal' %}
                {{ order.order_total|floatformat:2 }}
                {% endif %}
            </td>

            <td class="px-6 py-4">
                <a href="/invoice/{{ order.pk }}/" class="font-medium text-blue-600 hover:underline">View</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

Billing/templates/order_item_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6 ">
    <p class="text-center text-3xl font-bold">Edit {{ order_item.product.name }}</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="my-6">
            <p class="text-xl mt-2">Product</p>
            {% render_field form.product class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
        </div>
        <div class="my-6">
            <p class="text-xl my-2">Quantity</p>
            {% render_field form.quantity class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="2" %}
        </div>
        <div class="my-6">
            <p class="text-xl my-2">Batch No.</p>
            {% render_field form.batchno class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="2" %}
        </div>
        <div class="my-6">
            <p class="text-xl my-2">Price</p>
            {% render_field form.price class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="2" %}
        </div>
        {{ form.errors }}<br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Save Changes
        </button>
    </form>
</div>
{% endblock %}