Accounting/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accounting/', views.accounting),

    path('accounting/balance/', views.balance_sheet),
    path('accounting/balance/add/', views.add_balance),

    path('accounting/pnl/', views.pnl),
    path('accounting/pnl/sales/', views.sales),
    path('accounting/pnl/debits/', views.total_expenses),

    path('accounting/cr/', views.credits_view),
    path('accounting/cr/<str:credit_type>/', views.credits_type_view),
    path('accounting/cr/<str:credit_type>/add_credit/', views.add_credit),
    path('accounting/cr/<str:credit_type>/<int:credit_id>/edit/', views.edit_credit),

    path('accounting/de/', views.debits_view),
    path('accounting/de/<str:debit_type_param>/', views.debit_type_view),
    path('accounting/de/<str:debit_type>/add_debit_type/', views.add_debit_type_form),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/', views.debits_by_type_view),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/add_debit/', views.add_debits_form),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/edit/', views.edit_debit_type_form),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/<int:debit_id>/', views.sub_debits_view),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/<int:debit_id>/edit/', views.edit_debit_form),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/<int:debit_id>/add_debit/', views.add_subdebits_form),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/<int:debit_id>/<int:sub_debit_id>/', views.sub_debits_expand_view),
    path('accounting/de/<str:debit_type>/<int:debit_type_id>/debit/<int:debit_id>/<int:sub_debit_id>/edit/', views.sub_debits_edit_view),

    path('accounting/de/add_debit/', views.add_debit),
    path('accounting/de/debit/<int:debit_id>/edit/', views.edit_debit),

    path('accounting/debits_csv/', views.all_debits_csv, name='all_debits_csv'),
    path('accounting/credits_csv/', views.all_credits_csv, name='all_credits_csv'),
]

Formee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Users.views import index_request

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_request),
    path('', include('Stock.urls')),
    path('', include('Users.urls')),
    path('', include('Billing.urls')),
    path('', include('Accounting.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Stock/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view),
    path('stock/', views.stock_view),
    path('stock/add_product/', views.add_product_view),
    path('stock/product/<str:code>/', views.edit_product_view),
    path('stock/stock_report/', views.stock_report),
    path('stock/generate_quantity_summary_csv/', views.generate_quantity_summary_csv, name='generate_quantity_summary_csv'),
]

Accounting/models.py
from django.db import models
from Billing.models import Order
import datetime
from django.db.models import Sum


CREDIT_TYPE = (
    ('sales', 'Sales'),
    ('indirect', 'Indirect'),
    ('miscellaneous', 'Miscellaneous'),
)


class Credit(models.Model):
    name = models.CharField(max_length=200)
    amount = models.FloatField()
    receipt_number = models.PositiveIntegerField(blank=True, null=True)
    payment_type = models.CharField(max_length=20, default='Cash')
    transaction_number = models.CharField(max_length=25, default=0, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=False, editable=True, null=True)
    cheque_no = models.CharField(max_length=100, default="")
    bank_name = models.CharField(max_length=100, default="")
    note = models.CharField(max_length=100, default='')
    credit_type = models.CharField(max_length=20, choices=CREDIT_TYPE, default='sales')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.receipt_number is None:
            self.receipt_number = self.id
            super().save(update_fields=['receipt_number'])


HOW_CHOICES = (
    ('self', 'Self'),
    ('bank', 'Bank'),
    ('shop', 'Shop Cash'),
)
TYPE = (
    ('material purchase', 'Material Purchase'),
    ('fuel', 'Fuel Consumption'),
    ('wastage', 'Process Wastage'),
    ('labour', 'Labour Expenses'),
    ('freight', 'Freight and Carriage'),
    ('production overhead', 'Production Overhead'),
    ('utilities', 'Utilities'),
    ('maintenance', 'Maintenance and Repair'),
    ('insurance', 'Insurance'),
    ('property expenses', 'Property Expenses'),
    ('professional fees', 'Labour Expenses'),
    ('financial', 'Financial Expenses'),
    ('general', 'General Expenses'),
    ('selling distribution', 'Administrative Expenses'),
    ('administrative', 'Administrative Expenses'),
)


class DebitType(models.Model):
    PURCHASE = 'purchase'
    DIRECT = 'direct'
    INDIRECT = 'indirect'
    MISCELLANEOUS = 'miscellaneous'

    TYPE_CHOICES = (
        (PURCHASE, 'Purchase'),
        (DIRECT, 'Direct'),
        (INDIRECT, 'Indirect'),
        (MISCELLANEOUS, 'Miscellaneous'),
    )

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=15, choices=TYPE_CHOICES)
    parent_type = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Debit(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)
    reason = models.TextField(blank=True, null=True)
    debit_type = models.ForeignKey(DebitType, on_delete=models.CASCADE, null=True)

    def get_total_amount(self):
        subdebit_amounts = self.subdebit.aggregate(total_sum=Sum('amount'))['total_sum']
        return subdebit_amounts or self.amount

    def __str__(self):
        return self.name


Quantity_Choice = (
    ('kgs', 'KGS'),
    ('pieces', 'Pieces'),
)

Payment_Type = (
    ('cash', 'Cash'),
    ('upi', 'UPI'),
    ('cheque', 'Cheque'),
    ('net banking', 'Net Banking'),
)


class SubDebit(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    quantity_type = models.CharField(max_length=20, choices=Quantity_Choice, default='kgs')
    price = models.FloatField(default=0.0, null=True, blank=True)
    cgst = models.FloatField(default=0.0, null=True, blank=True)
    sgst = models.FloatField(default=0.0, null=True, blank=True)
    sub_amount = models.FloatField(default=0)
    amount = models.FloatField()
    date = models.DateField()
    reason = models.TextField(null=True, blank=True)
    debit = models.ForeignKey(Debit, on_delete=models.CASCADE)
    payment_type = models.CharField(max_length=100, choices=Payment_Type, default='cash')

    def __str__(self):
        return self.name

    @property
    def cgst_amount(self):
        amt = 0
        if self.cgst:
            amt = (self.price * self.quantity) * self.cgst / 100
        else:
            None

        return amt

    @property
    def sgst_amount(self):
        amt = 0
        if self.sgst:
            amt = (self.price * self.quantity) * self.sgst / 100
        else:
            None
        return amt

    @property
    def amount_without_gst(self):
        return self.amount - (self.sgst_amount + self.cgst_amount)


class Balance(models.Model):
    CHOICES = [
        ('Liability', 'Liability'),
        ('Asset', 'Asset'),
    ]

    name = models.CharField(max_length=100)
    reason = models.TextField(blank=True, null=True)
    balance_type = models.CharField(max_length=10, choices=CHOICES)

    def __str__(self):
        return self.name


class BalanceObject(models.Model):
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    sub_amount = models.FloatField(default=0)
    amount = models.FloatField()
    cgst = models.FloatField(default=0.0, null=True, blank=True)
    sgst = models.FloatField(default=0.0, null=True, blank=True)
    date = models.DateField()
    payment_mode = models.CharField(max_length=20, choices=Payment_Type)

    def __str__(self):
        return f"{self.name} - {self.amount}"

Accounting/forms.py
from django import forms
from .models import *


class CreditForm(forms.ModelForm):
    name = forms.CharField()
    amount = forms.FloatField()
    transaction_number = forms.CharField(required=False)
    payment_type = forms.CharField(required=False)
    date = forms.DateField(label='Created at', widget=forms.DateInput(attrs={'type': 'date'}),
                                 input_formats=['%Y-%m-%d'])
    cheque_no = forms.CharField(required=False)
    bank_name = forms.CharField(required=False)
    note = forms.CharField(required=False)
    credit_type = forms.CharField(required=False)

    class Meta:
        model = Credit
        fields = ['name', 'amount', 'payment_type', 'transaction_number', 'date', 'cheque_no',
                  'bank_name', 'note', 'credit_type']


class DebitTypeForm(forms.ModelForm):
    class Meta:
        model = DebitType
        fields = ['name']


class DebitTypeEditForm(forms.ModelForm):
    class Meta:
        model = DebitType
        fields = '__all__'


class DebitForm(forms.ModelForm):
    name = forms.CharField()
    reason = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Debit
        fields = ['name', 'reason']


class EditDebitForm(forms.ModelForm):
    amount = forms.FloatField(required=False)
    reason = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Debit
        fields = '__all__'


class SubDebitForm(forms.ModelForm):
    name = forms.CharField()
    quantity = forms.IntegerField(required=False)
    price = forms.FloatField(required=False)
    quantity_type = forms.ChoiceField(choices=Quantity_Choice, required=False)
    cgst = forms.IntegerField(required=False)
    sgst = forms.IntegerField(required=False)
    amount = forms.FloatField()
    reason = forms.CharField(widget=forms.Textarea, required=False)
    date = forms.DateField(label='Date', widget=forms.DateInput(attrs={'type': 'date'}), input_formats=['%Y-%m-%d'])
    payment_type = forms.ChoiceField(choices=Payment_Type)

    class Meta:
        model = SubDebit
        fields = ['name', 'quantity', 'price', 'quantity_type', 'cgst', 'sgst', 'amount', 'reason', 'date', 'payment_type']


class BalanceForm(forms.ModelForm):
    class Meta:
        model = Balance
        fields = '__all__'

Accounting/templates/add_debit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Add New Debit</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="my-4">
            <label class="text-xl">Name <i class="optional">*</i></label>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Tea" %}
        </div>
        <div class="flex gap-8 justify-between mt-4">
            <div class="w-full">
                <label class="text-xl">Note</label>
                {% render_field form.reason class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Add
            Debit
        </button>
    </form>
</div>

{% endblock %}

Accounting/templates/add_debitType.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Add New Debit Type</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="mt-6 mb-2">
            <p class="text-xl my-2">Debit Type Name <i class="optional">*</i></p>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Fuel / Labour" %}
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Add
            Debit Type
        </button>
    </form>
</div>

{% endblock %}

Accounting/templates/balance_sheet_add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Add New Balance Type</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="mt-6 mb-2">
            <p class="text-xl my-2">Balance Type <i class="optional">*</i></p>
            {% render_field form.balance_type class="w-full h-10 indent-2 rounded bg-transparent border-2"%}
        </div>
        <div class="mt-6 mb-2">
            <p class="text-xl my-2">Name <i class="optional">*</i></p>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Loans" %}
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Add Balance
        </button>
    </form>
</div>

{% endblock %}

Accounting/templates/credit_type.html
{% extends 'base.html' %}

{% block body %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li
    {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="flex w-11/12 m-auto gap-8 mt-4 mb-4 border-b-2">
    <div class="text-xl font-bold pb-2">
        <a href="/accounting/" class="text-blue-600 hover:underline">Accounting</a> >
        <a href="/accounting/cr/" class="text-blue-600 hover:underline">Credits</a> >
        <a href="/accounting/cr/{{ credit_type }}/" class="text-purple-600 hover:underline">{{ credit_type|title }}</a>
    </div>
</div>

<div class="flex justify-between mx-auto w-11/12">
    <div>
        <a href="add_credit/">
            <button class="px-4 py-2 bg-green-400 rounded whitespace-nowrap">Add Credit</button>
        </a>
    </div>
    <div class="flex-grow ml-8 flex-0">
        <form action="" class="flex">
            <input type="text" class="w-full h-10 border rounded px-4" name="credit_search"
                   placeholder="Search Credit">
            <div class="w-1/6 ml-2">
                <input type="date" id="start_date" name="start_date" class="h-10 border indent-1 rounded">
            </div>

            <div class="w-1/6 mx-2">
                <input type="date" id="end_date" name="end_date" class="h-10 border indent-1 rounded">
            </div>

            <button type="submit" class="ml-2 px-4 py-2 bg-green-400 rounded">Search</button>
        </form>
    </div>
</div>

<div class="w-11/12 m-auto flex justify-between gap-8 mb-16">

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg w-full mt-4">
        <table class="w-full text-sm text-left border">
            <thead class="text-xs uppercase">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Id
                </th>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Receipt Number
                </th>
                <th scope="col" class="px-6 py-3">
                    Amount
                </th>
                <th scope="col" class="px-6 py-3">
                    Payment Method
                </th>
                <th scope="col" class="px-6 py-3">
                    Credit Type
                </th>
                <th scope="col" class="px-6 py-3">
                    Date
                </th>
                <th scope="col" class="px-6 py-3">
                    Action
                </th>
            </tr>
            </thead>
            <tbody>
            {% for credit in credits %}
            <tr class="bg-white border-b">
                <td class="px-6 py-4">
                    {{ credit.pk }}
                </td>
                <th class="px-6 py-4 font-medium text-gray-900 whitespace-wrap">
                    {{ credit.name }}
                </th>
                <td class="px-6 py-4">
                    {{ credit.pk }}
                </td>
                <td class="px-6 py-4">
                    {{ credit.amount|floatformat:2 }}
                </td>
                <td class="px-6 py-4">
                    {{ credit.payment_type }}
                </td>
                <td class="px-6 py-4">
                    {{ credit.credit_type|title }}
                </td>
                <td class="px-6 py-4">
                    {{ credit.date|date:"F d, Y" }}
                </td>
                <td class="px-6 py-4">
                    <a href="{{ credit.id }}/edit/" class="font-medium text-blue-600 hover:underline">Edit</a>
                </td>
            </tr>
            {% endfor %}
            <tr class="bg-blue-600">
                <td colspan="8"></td>
            </tr>

            <tr>
                <td class="px-6 py-4" colspan="2"></td>
                <td class="px-6 py-4">Total Sales</td>
                <td class="px-6 py-4">{{ total_credits|floatformat:2 }}
                </td>
                <td class="px-6 py-4" colspan="4"></td>
            </tr>
            <tr class="bg-blue-600">
                <td colspan="8"></td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

Accounting/templates/credits_view.html
{% extends 'base.html' %}

{% block body %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li
    {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="flex w-11/12 m-auto border-b-2 gap-8 mt-4 mb-4">
    <div class="text-xl font-bold pb-2">
        <a href="/accounting/" class="text-blue-600 hover:underline">Accounting</a> >
        <a href="/accounting/cr/" class="text-purple-600 hover:underline">Credits</a>
    </div>
</div>

<div class="flex justify-start mx-auto w-11/12">
    <div class="flex-grow flex-0">
        <form action="" class="flex">
            <div class="mr-2">
                <input type="date" id="start_date" name="start_date" class="h-10 border indent-1 rounded">
            </div>

            <div class="mx-2">
                <input type="date" id="end_date" name="end_date" class="h-10 border indent-1 rounded">
            </div>

            <button type="submit" class="ml-2 px-4 py-2 bg-green-400 rounded">Search</button>
        </form>
    </div>
</div>

<div class="w-11/12 m-auto flex justify-between gap-8 mb-16">

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg w-full mt-4">
        <table class="w-full text-sm text-left border">
            <thead class="text-xs uppercase">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Id
                </th>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Amount(Paid Only)
                </th>
                <th scope="col" class="px-6 py-3">
                    Action
                </th>
            </tr>
            </thead>
            <tbody>
            {% for credit_type, total_credit in credit_sums %}
            <tr class="bg-white border-b">
                <td class="px-6 py-4">
                    {{ forloop.counter }}
                </td>
                <th class="px-6 py-4 font-medium text-gray-900 whitespace-wrap">
                    {{ credit_type|title }}
                </th>
                <td class="px-6 py-4">
                    {{ total_credit|floatformat:2 }}
                </td>
                <td class="px-6 py-4">
                    {% if request.GET.start_date and request.GET.end_date %}
                    <a href="{{ credit_type }}/?start_date={{ request.GET.start_date }}&end_date={{ request.GET.end_date }}"
                       class="font-medium text-blue-600 hover:underline">View</a>
                    {% else %}
                    <a href="{{ credit_type }}/" class="font-medium text-blue-600 hover:underline">View</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            <tr class="bg-blue-600">
                <td colspan="5"></td>
            </tr>

            <tr>
                <td class="px-6 py-4" colspan="1"></td>
                <td class="px-6 py-4">Total Sales</td>
                <td class="px-6 py-4">{{ total_credit_sum|floatformat:2 }}
                </td>
                <td class="px-6 py-4" colspan="4"></td>
            </tr>
            <tr class="bg-blue-600">
                <td colspan="5"></td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

Accounting/templates/debit_type_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Edit New Debit Type</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="mt-6 mb-2">
            <p class="text-xl my-2">Debit Type <i class="optional">*</i></p>
            {% render_field form.type class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Fuel / Labour" %}
        </div>
        <div class="mt-6 mb-2">
            <p class="text-xl my-2">Debit Type Name <i class="optional">*</i></p>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Fuel / Labour" %}
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Save Changes
        </button>
    </form>
</div>

{% endblock %}

Accounting/templates/debits_by_type_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-2/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Edit Debit</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="my-4">
            <label class="text-xl">Name <i class="optional">*</i></label>
            {% render_field form.debit_type class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Tea" %}
        </div>
        <div class="my-4">
            <label class="text-xl">Name <i class="optional">*</i></label>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Tea" %}
        </div>
        <div class="flex gap-8 justify-between mt-4">
            <div class="w-full">
                <label class="text-xl">Note</label>
                {% render_field form.reason class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Save Debit
        </button>
    </form>
</div>

{% endblock %}

Accounting/templates/sub_debit_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}

<div class="m-auto my-8 p-8 border-2 rounded-xl w-3/6" style="box-shadow: 0 25px 25px rgb(0 0 0 / 0.15);">
    <p class="text-center text-3xl font-bold">Add New Debit</p>
    <br>
    <hr>
    <form method="post">
        {% csrf_token %}
        <div class="my-4">
            <label class="text-lg my-2">Name <i class="optional">*</i></label>
            {% render_field form.name class="w-full h-10 indent-2 rounded bg-transparent border-2" placeholder="Tea" %}
        </div>

        <div class="flex gap-8 justify-between my-4">
            <div class="w-1/3">
                <label for="id_price" class="text-lg my-2">Price Per Unit</label>
                {% render_field form.price id="id_price" class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>
            <div class="w-1/3">
                <label for="id_quantity" class="text-lg my-2">Quantity</label>
                {% render_field form.quantity id="id_quantity" class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>
            <div class="w-1/3">
                <label class="text-lg my-2">Quantity Type</label>
                {% render_field form.quantity_type class="w-full h-10 indent-1 rounded bg-transparent border-2" %}
            </div>
        </div>

        <div class="flex gap-8 justify-between my-4">
            <div class="w-1/3">
                <label class="text-lg my-2" for="id_cgst">CGST%</label>
                {% render_field form.cgst id="id_cgst" class="w-full h-10 indent-1 rounded bg-transparent border-2" %}
            </div>
            <div class="w-1/3">
                <label class="text-lg my-2" for="id_sgst">SGST%</label>
                {% render_field form.sgst for="id_sgst" class="w-full h-10 indent-1 rounded bg-transparent border-2" %}
            </div>
            <div class="w-1/3">
                <label for="id_amount" class="text-lg my-2">Amount <i class="optional">*</i></label>
                {% render_field form.amount id="id_amount" class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>

        </div>

        <div class="flex gap-8 justify-between">
            <div class="w-1/3">
                <label class="text-lg my-2">Payment Type <i class="optional">*</i></label>
                {% render_field form.payment_type class="w-full h-10 indent-1 rounded bg-transparent border-2" placeholder="Eg: Ankoor" %}
            </div>
            <div class="w-1/3">
                <label class="text-lg my-2">Date <i class="optional">*</i></label>
                {% render_field form.date class="w-full h-10 indent-1 rounded bg-transparent border-2" placeholder="Eg: Ankoor" %}
            </div>
            <div class="w-1/3">
                <label class="text-lg my-2">Note</label>
                {% render_field form.reason class="w-full h-10 indent-2 rounded bg-transparent border-2" %}
            </div>
        </div>
        {{ form.errors }}
        <br>
        <button type="submit"
                class="w-full bg-green-400 rounded h-12 text-xl hover:drop-shadow-2xl duration-300 ease-in-out">Save
            Debit
        </button>
    </form>
</div>

<script>
    document.getElementById("id_quantity").addEventListener("input", calculateAmount);
    document.getElementById("id_price").addEventListener("input", calculateAmount);
    document.getElementById("id_cgst").addEventListener("input", calculateAmount);
    document.getElementById("id_sgst").addEventListener("input", calculateAmount);

    function calculateAmount() {
        const quantity = document.getElementById("id_quantity").value;
        const price = document.getElementById("id_price").value;
        const cgst = document.getElementById("id_cgst").value;
        const sgst = document.getElementById("id_sgst").value;
        const sub_amount = quantity * price;
        const amount = sub_amount + (sub_amount*cgst/100) + (sub_amount*sgst/100);

        document.getElementById("id_amount").value = amount.toFixed(2);
    }


</script>

{% endblock %}